apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: bookstore-connection
      port: 8080
      targetPort: 8080
      nodePort: 30001
