apiVersion: v1
kind: Service
metadata:
  name: mysql-standalone
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - name: http-mysql
      port: 3306
      targetPort: 3306
      nodePort: 30003
  selector:
    app: mysql-standalone
