apiVersion: v1
kind: Service
metadata:
  name: mysql-serivce
spec:
  type: NodePort
  selector:
    db: mysql
  ports:
    - name: mysql-connection
      port: 3306
      targetPort: 3306
      nodePort: 30006
