apiVersion: v1
kind: Pod
metadata:
  name: mysql-standalone
  labels:
    app: mysql-standalone
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Wipacc@123
        - name: MYSQL_USER
          value: sa
        - name: MYSQL_DATABASE
          value: bookstore
      ports:
        - containerPort: 3306
          name: mysql
