apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: mysql-standalone
  labels:
    app: mysql-standalone
    version: v1
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      # imagePullPolicy: Never
      env:
        # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Wipacc@123
        - name: MYSQL_USER
          value: sa
        - name: MYSQL_DATABASE
          value: bookstore
      ports:
        - containerPort: 3306
          name: mysql
