apiVersion: v1
kind: Service
metadata:
  name: mysql-standalone
spec:
  type: NodePort
  selector:
    app: mysql-standalone
  ports:
    - name: mysql-connection
      port: 3306
      targetPort: 3306
      nodePort: 30006
